### ISSUE TITLE
spaceship doesn't DWIM

### ISSUE THREAD

**Issue by karenetheridge** [rjbs/Number-Tolerant#2]
It appears this is a bug?

    diff --git a/t/plusminus.t b/t/plusminus.t
    index ec6abe5..e424849 100644
    --- a/t/plusminus.t
    +++ b/t/plusminus.t
    @@ -1,4 +1,4 @@
    -use Test::More tests => 48;
    +use Test::More;
     
     use strict;
     use warnings;
    @@ -37,6 +37,15 @@ is( (4 <=> $guess), -1,   " ... 4 <=> it is -1");
     is( (5 <=> $guess),  0,   " ... 5 <=> it is  0");
     is( (6 <=> $guess), +1,   " ... 6 <=> it is +1");
     
    +is( (4.4 <=> $guess), -1,  " ... 4.4 is less than it");
    +is( (4.5 <=> $guess),  0,  " ... 4.5 is equal to it");
    +is( (5.0 <=> $guess),  0,  " ... 5.0 is equal to it");
    +is( (5.5 <=> $guess),  0,  " ... 5.5 is equal to it");
    +is( (5.6 <=> $guess),  1,  " ... 5.6 is more than it");
    +
     # ... and now more of the same, BACKWARDS
     
     ok($guess != 0.0,         " ... it isn't equal to 0.0");
    @@ -74,3 +80,5 @@ is( ($guess <=> 6), -1,   " ... 6 <=> it is +1");
       isa_ok($tol, 'Number::Tolerant');
            is($tol, "10 +/- 2", "plus_or_minus");
     }
    +
    +done_testing;

**Comment by rjbs** [comment]
I'm closing this ticket, because it claims too many things, some of them clearly incorrect.
For example:

> And infinity isn't "any number" - it's infinity - greater than any real number. Mr. Signes, what were you 
> smoking? :)

An infinite tolerance is not infinity.  It is a tolerance for any value.  So, yes, it is any number.

How do you compare it with `>` and `<`?  Nothing is greater or less than it.  We only implement these because we must.  Otherwise, they'd be left undefined.  Perl 5 doesn't have "can compare for numeric equality but not sort" role.

In general, tolerances sort by their chief value, but not all tolerances have one.  For example, (5 -10 +5) is targeting 5, but will allow -5 or 10.  The midpoint is 2.5, but the value for sorting is 5.  Basically, the sorting methods are there only to make things slightly less crazy.  They do not have, nor I think *can* they have, some canonically correct and extremely obvious behavior.  

If there are specific failures, please point them out.  There may be some above, but if so, I think I've lost sight of them.

**Comment by karenetheridge** [comment]
> In general, tolerances sort by their chief value

This appears to contradict your earlier statements about `<=>` -- https://github.com/rjbs/Number-Tolerant/issues/2#issuecomment-48137393.  Which is correct?

I'm trying out a new branch that makes that change to `<=>`, and on the whole, the results look a lot more sane.

> An infinite tolerance is not infinity. It is a tolerance for any value. So, yes, it is any number.

This deserves being spelled out explicitly in the documentation, as that's not how I interpreted the use of infinity in a tolerance.

**Comment by rjbs** [comment]
> This appears to contradict your earlier statements about <=> -- #2 (comment). Which is correct?

My later statement is correct.

You say that you have changes that make things "look more sane," but this implies that there is some "canonically correct and extremely obvious behavior" for sorting, which I said I didn't think existed.  Or at least it implies that some behaviors are way better than others… but I'm not sure what you're seeing that's obviously better.

I agree that `<=>` should always return 0 for an infinite tolerance, though, as your test suggested.

My big question here, though is: what is the use case for sorting tolerances?

**Comment by karenetheridge** [comment]
Sorting doesn't have anything to do with this. That's just one use of `<=>`.  The change, rather, aims to make the behaviour of the spaceship operator consistent with the behaviour of `<`, `==` and `>`, where previous it was not.

That is: if `$a < $b` is true, then `$a <=> $b` should *ALWAYS* return -1, surely?

**Comment by rjbs** [comment]
fixed by #5
